
import type { Opportunity } from '@/hooks/use-auth';
import { Timestamp } from 'firebase/firestore';

export const preloadedOpportunities: Opportunity[] = [
  {
    id: 'dbf-competition-2025',
    title: 'AIAA Design, Build, Fly Competition',
    description: 'An international RC aircraft competition focusing on Integrated Design & Systems Engineering.',
    category: 'external',
    externalType: 'Competition',
    organization: 'AIAA Foundation',
    eligibility: 'University/College (Global, India eligible)',
    deadline: '2025-10-31T21:00:00.000Z', // 5:00 PM ET
    applicationInstructions: 'Proposal Phase OPEN. Key Deadline: 5:00 PM ET, October 31, 2025 (Proposal Submission). AIAA Foundation grants; Potential $750 travel stipend for 1st place representative.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'sae-aero-design-2025',
    title: 'SAE Aero Design',
    description: 'RC Plane competition focused on Payload Efficiency (Multi-Engine Cargo Mission).',
    category: 'external',
    externalType: 'Competition',
    organization: 'SAE International',
    eligibility: 'University/College',
    deadline: '2025-10-24T03:59:59.000Z', // 11:59:59 PM ET on Oct 23
    applicationInstructions: 'Lottery Interest OPEN. Key Deadline: 11:59:59 PM ET, October 23, 2025 (Lottery Interest Closes). Host/Location: Florida (East) or Texas (West), USA. No travel support; requires team fundraising/sponsorship.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'boeing-national-aeromodelling-2025',
    title: 'Boeing National Aeromodelling Competition',
    description: 'RC Plane competition focused on Payload & Precision (Domestic Focus).',
    category: 'external',
    externalType: 'Competition',
    organization: 'Boeing India',
    eligibility: 'Students (National)',
    deadline: '2025-10-19T23:59:59.000Z', // Approx. date
    applicationInstructions: 'Zonal rounds ongoing/upcoming. Key Deadline: ~October 19, 2025 (Abstract Submission - 20 days prior to zonal date). Host/Location: India (Various Zonal IITs/KIIT). Support: INR 5,000 reimbursement for qualified teams to cover material costs.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'auvsi-suas-2025',
    title: 'AUVSI SUAS Competition',
    description: 'UAS/VTOL hands-on design & fly-off competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'AUVSI',
    eligibility: 'University/College',
    deadline: '2025-10-30T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: October 30, 2025 (Letter of Intent). Host/Location: Churchville, MD, USA. Support: Potential $1,000 stipend to the university for winning teams. Requires pilot to hold FAA Part 107 or equivalent certification.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'nasa-student-launch-2025',
    title: 'NASA Student Launch',
    description: 'Rocketry challenge focused on integrated launch systems.',
    category: 'external',
    externalType: 'Competition',
    organization: 'NASA',
    eligibility: 'College/University',
    deadline: '2025-09-22T23:59:59.000Z',
    applicationInstructions: 'Proposal Phase OPEN. Key Deadline: September 22, 2025. Host/Location: USA (Alabama). No travel support; team responsible for travel funding.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'vfs-design-competition-2026',
    title: 'VFS Student Design Competition',
    description: 'Conceptual design competition for a Hybrid Electric Tiltrotor.',
    category: 'external',
    externalType: 'Competition',
    organization: 'Vertical Flight Society',
    eligibility: 'University/College',
    deadline: '2026-02-01T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: February 1, 2026 (Letter of Intent). Global submission-based. Support: Total $12,500 in cash prizes. $1,000 travel stipend for presenting at the VFS Forum.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'american-rocketry-challenge-2025',
    title: 'American Rocketry Challenge',
    description: 'Rocketry competition for students.',
    category: 'external',
    externalType: 'Competition',
    organization: 'National Association of Rocketry',
    eligibility: 'Middle/High School (Global, India eligible)',
    deadline: '2025-12-06T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: December 6, 2025. Host/Location: USA (Virginia). No travel support; requires team fundraising/sponsorship.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'in-space-cansat-2026',
    title: 'IN-SPACe CANSAT INDIA',
    description: 'Model Rocketry/CANSAT competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'ISRO/IN-SPACe',
    eligibility: 'Undergraduate Students (Indian teams)',
    deadline: '2026-08-31T23:59:59.000Z', // Anticipated
    applicationInstructions: 'Currently Closed. Anticipated to open mid-2025 for the next cycle. Host/Location: India (National). Support: Finalists\' logistics supported by ISRO/IN-SPACe.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'ignite-innovation-challenge-2025',
    title: 'IGNITE Innovation Challenge',
    description: 'Multi-disciplinary innovation challenge.',
    category: 'external',
    externalType: 'Competition',
    organization: 'Yato.ai',
    eligibility: 'School/College (Age 14-25)',
    deadline: '2025-08-15T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: August 15, 2025. Host/Location: India (Chhattisgarh). Support: Stay, Meals, and Kit Included.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'interlatam-cansat-challenge-2025',
    title: 'INTERLATAM CanSat Challenge',
    description: 'CanSat / Rocketry competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'INTERLATAM',
    eligibility: 'University/College',
    deadline: '2025-11-28T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: November 28, 2025. Host/Location: Mexico (Mexico City). No travel support; requires team fundraising.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'sae-india-aero-thon-2025',
    title: 'SAE INDIA Aero-Thon',
    description: 'UAS (Unmanned Aerial System) competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'SAE INDIA',
    eligibility: 'Indian students',
    deadline: '2025-11-13T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: November 13, 2025. Host/Location: India. Support: Industry mentorship.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'aero-dominion-2025',
    title: 'Aero DOMINION',
    description: 'RC Craft competition focused on Maneuver Performance & Robustness.',
    category: 'external',
    externalType: 'Competition',
    organization: 'Various',
    eligibility: 'National and International Teams',
    deadline: '2025-12-31T23:59:59.000Z', // Varies
    applicationInstructions: 'Ongoing/Upcoming. Key Deadline: Varies by round (Check official website for specific phase deadlines). Host/Location: Global (Competition likely held in India). Support: Total award pool of INR 1,25,000 for winning teams.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'boeing-aeromodelling-iit-bombay-2025',
    title: 'Boeing Aeromodelling at IIT Bombay',
    description: 'RC/Drone competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'IIT Bombay',
    eligibility: 'Indian colleges',
    deadline: '2025-12-31T23:59:59.000Z', // Open registration
    applicationInstructions: 'Open since October 18, 2025 (Registration Period). Host/Location: Mumbai, India. Support: IIT/industry funding.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'drone-racing-league-vit-2025',
    title: 'Drone Racing League VIT',
    description: 'Drone Racing competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'VIT Chennai',
    eligibility: 'Indian teams',
    deadline: '2025-11-30T23:59:59.000Z',
    applicationInstructions: 'Open now. Key Deadline: November 2025. Host/Location: Tamil Nadu, India. Support: Prizes & offers.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
  {
    id: 'cansat-competition-usa-2026',
    title: 'CanSat Competition USA',
    description: 'CanSat / Space Systems competition.',
    category: 'external',
    externalType: 'Competition',
    organization: 'AAS & AIAA',
    eligibility: 'University/College',
    deadline: '2026-05-31T23:59:59.000Z', // TBD, placeholder
    applicationInstructions: 'Application Link Open. Key Deadline: TBD (Launch June 2026). Host/Location: USA (Virginia). No travel support; teams explicitly fund all travel/lodging.',
    status: 'approved',
    createdAt: Timestamp.fromDate(new Date()),
    authorEmail: 'system@aura.com',
    authorName: 'AURA System',
  },
];
